### ISSUE TITLE
可以截图,但是点开始没反应

### ISSUE THREAD

**Issue by vejunbl** [KaleidoZhouYN/nikke_script#2]
模拟器型号雷电模拟器9.0.29(9)

**Comment by KaleidoZhouYN** [comment]
有按照视频中的进入拦截战boss出来之后才按开始吗？

**Comment by hxylol** [comment]
雷电9.0.29(9)，等boss出来按的没反应，按f也没出现防御

**Comment by KaleidoZhouYN** [comment]
有安装python么？

**Comment by hxylol** [comment]
> 有安装python么？

谢谢大佬，我还以为全部都打包了，明天来试试

**Comment by hxylol** [comment]
> 不是，我打包可能有点问题，如果你没安装python，我可以再打一个包

感谢感谢，我这边电脑没装Python，大佬早点休息~

**Comment by suanchengpai** [comment]
用了结果没我手动打的高，是哪里有问题么

**Comment by KaleidoZhouYN** [comment]
最新打包v1.1_beta，不需要python依赖
